@BaseURL = http://localhost:3003/api
@contentType = application/json
@dateNow = {{$datetime iso8601}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo2LCJyb2xlIjoidXNlciJ9LCJleHAiOjE1NjE4Nzc2MzUsImlhdCI6MTU1OTI4NTYzNX0.Ne2orvPH-SFj-QIjtP43FIBwuFsfvKZsnki5L27qeLs

### create project
POST {{BaseURL}}/project/create HTTP/1.1
content-type: {{contentType}}
token: {{token}}

{
	"name": "测试项目{{dateNow}}",
	"description": "测试项目{{dateNow}}",
  "users": ["3", "6"]
}

### get project
GET {{BaseURL}}/project/info/1022 HTTP/1.1
token: {{token}}

### get projects
GET {{BaseURL}}/project
  ?page=1
  &size=20
  &keyword=测试
token: {{token}}

### update project
POST {{BaseURL}}/project/update HTTP/1.1
content-type: {{contentType}}
token: {{token}}

{
	"id": "1003",
	"name": "测试项2-{{dateNow}}",
	"description": "测试项目-{{dateNow}}",
  "users": ["6"]
}

### delete project
DELETE {{BaseURL}}/project/delete HTTP/1.1
content-type: {{contentType}}
token: {{token}}

{
	"id": "1022"
}

### migrate project owner
POST {{BaseURL}}/project/migrateOwner HTTP/1.1
content-type: {{contentType}}
token: {{token}}

{
	"id": "1013",
  "ownerId": "3"
}
